spring:
  application:
    name: the-wild-oasis-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL:false}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/v1/the-wild-oasis
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME}
  expiration-time-unit: ${JWT_EXPIRATION_TIME_UNIT}

refresh-token:
  expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}
  expiration-time-unit: ${REFRESH_TOKEN_EXPIRATION_TIME_UNIT}
  absolute-expiration-time: ${REFRESH_TOKEN_ABSOLUTE_EXPIRATION_TIME}
  absolute-expiration-time-unit: ${REFRESH_TOKEN_ABSOLUTE_EXPIRATION_TIME_UNIT}
