name: Deploy Lodge Core Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_DEPLOY_PATH: ${{ secrets.SERVER_DEPLOY_PATH }}
  DOCKER_IMAGE_NAME: lodge-core-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # clone from repo to VM
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Save Docker image to tar
        run: |
          docker save -o ${{ env.DOCKER_IMAGE_NAME }}.tar ${{ env.DOCKER_IMAGE_NAME }}
          ls -la *.tar

      - name: Transfer Docker image to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          source: "${{ env.DOCKER_IMAGE_NAME }}.tar"
          target: ${{ env.SERVER_DEPLOY_PATH }}

      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            cd ${{ env.SERVER_DEPLOY_PATH }}
            
            echo "Stopping existing container..."
            docker stop ${{ env.DOCKER_IMAGE_NAME }}-container || echo "Container already stopped"
            docker rm ${{ env.DOCKER_IMAGE_NAME }}-container || echo "Container already deleted"
            docker rmi ${{ env.DOCKER_IMAGE_NAME }}  || echo "Image already deleted"
            
            echo "Loading new Docker image..."
            docker load -i ${{ env.DOCKER_IMAGE_NAME }}.tar

            echo "Starting new container..."
            docker run -d \
              --name ${{ env.DOCKER_IMAGE_NAME }}-container \
              -p 8080:8080 \
              --env-file .env \
              --restart unless-stopped \
              --network lodge-core-net \
              ${{ env.DOCKER_IMAGE_NAME }}
            
            echo "Deployment completed!"
            docker ps | grep ${{ env.DOCKER_IMAGE_NAME }}